name:                refurb-example
version:             0.1.0.0
synopsis:            Tools for maintaining a database
description:         Tools for maintaining a database
homepage:            https://github.com/ConferHealth/refurb#readme
maintainer:          it@confer.care
copyright:           2017 Confer Health, Inc.
category:            Database

default-extensions:
  - Arrows
  - ConstraintKinds
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

dependencies:
  - base >= 4.7 && < 5
  - classy-prelude
  - postgresql-simple
  - refurb

ghc-options:
  - -Wall
  - -Werror
  - -O2

executables:
  refurb-example-exe:
    main: Main.hs
