resolver: lts-14.20
packages:
  - .
  - example
extra-deps:
  - composite-base-0.6.0.0
  - composite-opaleye-0.6.0.0
  - these-lens-1
  # - thyme-0.3.5.5
flags: {}
extra-package-dbs: []
# nix:
#   enable: true
#   packages:
#     - postgresql
#     - zlib
