resolver: lts-11.9
packages:
  - .
  - example
extra-deps:
  - composite-base-0.5.4.0
  - composite-opaleye-0.5.4.0
  - thyme-0.3.5.5
flags: {}
extra-package-dbs: []
# nix:
#   enable: true
#   packages:
#     - postgresql
#     - zlib
