resolver: lts-8.6
packages:
  - .
  - example
extra-deps:
  - composite-base-0.3.1.0
  - composite-opaleye-0.3.1.0
flags: {}
extra-package-dbs: []
# nix:
#   enable: true
#   packages:
#     - postgresql
#     - zlib
