resolver: lts-9.13
packages:
  - .
  - example
extra-deps:
  - composite-base-0.5.3.0
  - composite-opaleye-0.5.3.0
flags: {}
extra-package-dbs: []
# nix:
#   enable: true
#   packages:
#     - postgresql
#     - zlib
